rpc_url: "https://mainnet.helius-rpc.com/?api-key=b71e405d-e435-4d7e-a381-f6c32a6e9e10"
websocket_url: "wss://mainnet.helius-rpc.com/?api-key=b71e405d-e435-4d7e-a381-f6c32a6e9e10"
priority_fee: 70000
slippage: 0.3
buy_amount_sol: 0.005
take_profit: 1.1
stop_loss: 0.8
auto_sell_after: 60
min_liquidity: 0.5
raydium_program_id: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
