# config.yaml
env: .env

liquidity_threshold_sol: 0.5
honeypot_check: true

jupiter:
  slippage_bps:    50
  timeout_seconds: 60
  reinvest:        false
  swap_amount:     1000000    # nombre de lamports (1 000 000 = 0.001 SOL) ou ajuster pour tests

volatility:
  use_dynamic: true
  multiplier:   1.5

public_key: ${YOUR_PUBLIC_KEY}
