name: 🧪 CI Tests

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies & package
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Expose project root to PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Run pytest
        run: pytest -q
