# .github/workflows/deploy.yml
name: CI & Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  test:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies & package
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Expose project root to PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Run pytest
        run: pytest -q

  deploy:
    name: 🚀 Deploy to Railway
    needs: test
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js (required for Railway CLI)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Railway CLI (via npm)
        run: npm install -g @railway/cli

      - name: Deploy service "nono"
        run: |
          railway up \
            --project $RAILWAY_PROJECT_ID \
            --service nono \
            --token $RAILWAY_TOKEN
